language: java
jdk: oraclejdk11

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install -B

after_success:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=serhva132/my-hello-world
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME